
server:
  port: 8070

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmall_study
    username: root
    password: 970821
# dubbo
  dubbo:
    application: user-service
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo
    registry:
      address: 192.168.123.27:2181
      protocol: zookeeper
logging:
  level:
    root: info
