server:
  port: 8082

logging:
  level:
    root: info
spring:
  thymeleaf:
#    关闭thymeleaf缓存，热部署
    cache: false
    #松校验
    mode: LEGACYHTML5
  dubbo:
    #    应用名称
    application: item-web
    #    扫描目录
    base-package: com.atguigu.gmall
    #    协议名称
    protocol:
      name: dubbo
    #      zookeeper设置
    registry:
      #      zookeeper地址
      address: 192.168.123.27:2181
      #      zookeeper协议名称
      protocol: zookeeper
    consumer:
      #      服务超时时间
      timeout: 600000
      #      不检查服务是否存在
      check: false