
server:
  port: 8076

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmall_study
    username: root
    password: 970821
# dubbo
  dubbo:
    application: order-service
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo
    registry:
      address: 192.168.123.27:2181
      protocol: zookeeper
  #redis
  redis:
    host: 192.168.123.27
    port: 6379
    database: 0
    pool:
      max-wait: 1000

logging:
  level:
    root: info
  #mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true